"""Re-export scanners from wcag_backend.scanners for compatibility."""

# Import everything from wcag_backend.scanners
from wcag_backend.scanners import (
    BaseScanner,
    AxeScanner,
    Pa11yScanner,
    LighthouseScanner,
    HTMLValidatorScanner,
    ContrastChecker,
    KeyboardScanner,
    ARIAScanner,
    SEOAccessibilityScanner,
    FormsScanner,
    LinkTextScanner,
    ImageAltScanner,
    MediaScanner,
    TouchTargetScanner,
    ReadabilityScanner,
    InteractiveScanner,
    ColorOnlyScanner,
    HoverContentScanner,
    MultipleWaysScanner,
    PointerGesturesScanner,
    ConsistentNavigationScanner,
    CharacterShortcutsScanner,
    FocusObscuredScanner,
    MediaAccessibilityScanner,
    SCANNERS,
)

__all__ = [
    "BaseScanner",
    "AxeScanner",
    "Pa11yScanner",
    "LighthouseScanner",
    "HTMLValidatorScanner",
    "ContrastChecker",
    "KeyboardScanner",
    "ARIAScanner",
    "SEOAccessibilityScanner",
    "FormsScanner",
    "LinkTextScanner",
    "ImageAltScanner",
    "MediaScanner",
    "TouchTargetScanner",
    "ReadabilityScanner",
    "InteractiveScanner",
    "ColorOnlyScanner",
    "HoverContentScanner",
    "MultipleWaysScanner",
    "PointerGesturesScanner",
    "ConsistentNavigationScanner",
    "CharacterShortcutsScanner",
    "FocusObscuredScanner",
    "MediaAccessibilityScanner",
    "SCANNERS",
]
